TeacherApp/Controllers/AdminPanelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TeacherApp.Models;


namespace TeacherApp.Controllers
{
    public class AdminPanelController : Controller
    {
        private readonly TeacherAppContext _context;

        public AdminPanelController(TeacherAppContext context)
        {
            _context = context;
        }


        public IActionResult Index()
        {
            return View();
        }

        // GET: Admin/Login
        public IActionResult AdminPanelLogin()
        {
            return View();
        }
        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }
        public IActionResult Reset()
        {
            return View();
        }
        public IActionResult Dashboard()
        {
            return View();
        }
        public IActionResult Statistics()
        {
            return View();
        }

        // POST: AdminPanel/Dashboard
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public int AdminPanelLogin(string username, string password)
        {
            Person p = (from Person in _context.Persons
                        where Person.Email == username && Person.Password == password && Person.IsAdmin == true
                        select Person).FirstOrDefault();
            if (p != null)
            {
                return p.ID;
            }
            return 0;
        }

        // GET: Teachers/Create
        public IActionResult CreateTeacher()
        {
            return View();
        }

        // POST: Teachers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateTeacher([Bind("ID,FirstName,LastName,Password,Phone,Gender,Email,Address,DateOfBirth,Degree,Institution,ActiveSince,Enrolled,Graduated,Rating,About,LessonPrice,ImagePath")] Teacher teacher)
        {
            if (ModelState.IsValid)
            {
                _context.Add(teacher);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(teacher);
        }



        // GET: Courses/Create
        public IActionResult CreateCourse()
        {
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateCourse([Bind("CourseID,CourseName,Credits")] Course course)
        {
            if (ModelState.IsValid)
            {
                _context.Add(course);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }



















    }

}

TeacherApp/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TeacherApp.Models;

namespace TeacherApp.Controllers
{
    public class CoursesController : Controller
    {
        private readonly TeacherAppContext _context;

        public CoursesController(TeacherAppContext context)
        {
            _context = context;
        }

        // GET: Courses
        public async Task<IActionResult> Index()
        {
            if (Request.Cookies["userEmail"] != null && Request.Cookies["userPassword"] != null)
                return View(await _context.Courses.ToListAsync());

            return View("~/Views/Home/Index.cshtml");
        }

        // GET: Courses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .SingleOrDefaultAsync(m => m.CourseID == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // GET: Courses/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CourseID,CourseName,Credits")] Course course)
        {
            if (ModelState.IsValid)
            {
                _context.Add(course);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        // GET: Courses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses.SingleOrDefaultAsync(m => m.CourseID == id);
            if (course == null)
            {
                return NotFound();
            }
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CourseID,CourseName,Credits")] Course course)
        {
            if (id != course.CourseID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(course);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(course.CourseID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        // GET: Courses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .SingleOrDefaultAsync(m => m.CourseID == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var course = await _context.Courses.SingleOrDefaultAsync(m => m.CourseID == id);
            _context.Courses.Remove(course);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseExists(int id)
        {
            return _context.Courses.Any(e => e.CourseID == id);
        }
        public IActionResult SearchResults()
        {
            return View();
        }
    }

}

TeacherApp/Controllers/TeachersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TeacherApp.Models;

namespace TeacherApp.Controllers
{
    public class TeachersController : Controller
    {
        private readonly TeacherAppContext _context;

        public TeachersController(TeacherAppContext context)
        {
            _context = context;
        }

        // GET: Teachers
        public async Task<IActionResult> Index(string searchString)
        {

            var teachers = from teacher in _context.Teachers
                            select teacher;

            if (!String.IsNullOrEmpty(searchString))
            {
                teachers = teachers.Where(t => t.FullName().Contains(searchString));
            }

            return View(await teachers.ToListAsync());

        }

        [HttpPost]
        public async Task<IActionResult> AddReview(int teacherID, string text, int rating)
        {
            // test user login
            if (Request.Cookies["userID"] == null)
            {
                Response.StatusCode = (int) HttpStatusCode.BadRequest;
                return Json(new { status = "error", message = "Please sign in to submit a review" });
            }
            int personID;

            // try to get userID from cookie
            try
            {
                personID = Int32.Parse(Request.Cookies["userID"]);
            }
            catch (Exception e)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new { status = "error", message = "Failed to get user details. " + e.Message });
            }

            Teacher teacher = await _context.Teachers
                .SingleAsync(t => t.ID == teacherID);
            _context.Entry(teacher)
                .Collection(t => t.Reviews)
                .Load();
            Person person = await _context.Persons
                .SingleAsync(p => p.ID == personID);

            var previousReview = from r in _context.Reviews
                                 where r.PersonID == person.ID
                                 where r.TeacherID == teacher.ID
                                 select r;
            // a review already exists for this user
            if (previousReview.ToList().Count > 0)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new
                {
                    status = "error",
                    message = "A review for " + teacher.FullName() + " Already exists from user"
                });
            }

            Review review = new Review
            {
                Published = DateTime.Now,
                Teacher = teacher,
                Rating = rating,
                ReviewContent = text,
                Person = person,
            };

            // will also add a new entry to Reviews table
            teacher.Reviews.Add(review);
            person.ReviewsSubmittedByUser.Add(review);
            _context.Reviews.Add(review);
            teacher.UpdateRating();
            _context.SaveChanges();
            Response.StatusCode = (int)HttpStatusCode.OK;
            return Json(new
            {
                status = "success",
                message = "review submited successfuly"
            });
        }

        // GET: Teachers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teachers
                .SingleOrDefaultAsync(m => m.ID == id);

            if (teacher == null)
            {
                return NotFound();
            }

            // load teacher reviews 
            _context.Entry(teacher)
                .Collection(t => t.Reviews)
                .Load();

            // load teacher courses
            _context.Entry(teacher)
                .Collection(t => t.TeachersCourses)
                .Load();

            // load person for all teacher reviews
            var teacherReviews = _context.Reviews.Where(r => r.TeacherID == id);
            foreach (var r in teacherReviews)
            {
                _context.Entry(r).Reference(x => x.Person).Load();
            }
          

            return View(teacher);
        }

        // GET: Teachers/Create
        public IActionResult Create()
        {
            return View();
        }       
        // GET: Teachers/AllTeachers
        public IActionResult AllTeachers()
        {
            return View();
        }

        // POST: Teachers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,FirstName,LastName,Password,Phone,Gender,Email,Address,DateOfBirth,Degree,Institution,ActiveSince,Enrolled,Graduated,Rating,About,LessonPrice,ImagePath")] Teacher teacher)
        {
            if (ModelState.IsValid)
            {
                _context.Add(teacher);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(teacher);
        }

        // GET: Teachers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teachers.SingleOrDefaultAsync(m => m.ID == id);
            if (teacher == null)
            {
                return NotFound();
            }
            return View(teacher);
        }

        // POST: Teachers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,FirstName,LastName,Password,Phone,Gender,Email,Address,DateOfBirth,Degree,Institution,ActiveSince,Enrolled,Graduated,Rating,About,LessonPrice,ImagePath")] Teacher teacher)
        {
            if (id != teacher.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(teacher);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeacherExists(teacher.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(teacher);
        }

        // GET: Teachers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teachers
                .SingleOrDefaultAsync(m => m.ID == id);
            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacher);
        }

        // POST: Teachers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var teacher = await _context.Teachers.SingleOrDefaultAsync(m => m.ID == id);
            _context.Teachers.Remove(teacher);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TeacherExists(int id)
        {
            return _context.Teachers.Any(e => e.ID == id);
        }
    }
}

TeacherApp/Views/AdminPanel/CreateTeacher.cshtml
@model TeacherApp.Models.Teacher

@{
    ViewData["Title"] = "CreateTeacher";

}
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="~/css/UserSignUp.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="assets/css/bootstrap.css">
    <!-- Website CSS style -->
    <link rel="stylesheet" type="text/css" href="assets/css/main.css">
    <!-- Website Font style -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <!-- Google Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>

</head>
<body>
    <div class="container">
        <div class="row main">
            <div class="panel-heading">
                <div class="panel-title text-center">

                </div>
            </div>
            <div class="main-login main-center">

                <form asp-action="CreateTeacher">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group">
                        <label asp-for="FirstName" class="cols-sm-2 control-label">First Name</label>
                        <div class="cols-sm-10">
                            <div class="input-group">
                                <span asp-validation-for="FirstName" class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
                                <input asp-for="FirstName" type="text" class="form-control" placeholder="Enter your First Name" />
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label asp-for="LastName" class="cols-sm-2 control-label">Last Name</label>
                        <div class="cols-sm-10">
                            <div class="input-group">
                                <span asp-validation-for="LastName" class="input-group-addon"><i class="far fa-user" aria-hidden="true"></i></span>
                                <input asp-for="LastName" type="text" class="form-control" placeholder="Enter your Name" />
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label asp-for="Password" class="cols-sm-2 control-label">Password</label>
                        <div class="cols-sm-10">
                            <div class="input-group">
                                <span asp-validation-for="Password" class="input-group-addon"><i class="fa fa-lock fa" aria-hidden="true"></i></span>
                                <input asp-for="Password" type="password" class="form-control" placeholder="Enter your Password" />
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label asp-for="Phone" class="cols-sm-2 control-label">Phone</label>
                        <div class="cols-sm-10">
                            <div class="input-group">
                                <span asp-validation-for="Phone" class="input-group-addon"><i class="fas fa-phone-volume" aria-hidden="true"></i></span>
                                <input asp-for="Phone" type="text" class="form-control" placeholder="Enter your Phone" />
                            </div>
                        </div>
                    </div>


                    <div class="form-group">
                        <label asp-for="Gender" class="cols-sm-2 control-label">Gender</label>
                        <div class="cols-sm-10">
                            <div class="input-group">
                                <span asp-validation-for="Gender" class="input-group-addon"><i class="fas fa-transgender" aria-hidden="true"></i></span>
                                <input asp-for="Gender" type="text" class="form-control" placeholder="Enter your Gender" />
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label asp-for="Email" class="cols-sm-2 control-label">Your Email</label>
                        <div class="cols-sm-10">
                            <div class="input-group">
                                <span asp-validation-for="Email" class="input-group-addon"><i class="fa fa-envelope fa" aria-hidden="true"></i></span>
                                <input asp-for="Email" type="text" class="form-control" placeholder="Enter your Email" />
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label asp-for="Address" class="cols-sm-2 control-label">Address</label>
                        <div class="cols-sm-10">
                            <div class="input-group">
                                <span asp-validation-for="Address" class="input-group-addon"><i class="fas fa-map-marker-alt" aria-hidden="true"></i></span>
                                <input asp-for="Address" type="text" class="form-control" placeholder="Enter your Adress" />
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label asp-for="DateOfBirth" class="cols-sm-2 control-label">Date Of Birth</label>
                        <div class="cols-sm-10">
                            <div class="input-group">
                                <span asp-validation-for="DateOfBirth" class="input-group-addon"><i class="fas fa-birthday-cake" aria-hidden="true"></i></span>
                                <input asp-for="DateOfBirth" type="date" class="form-control" placeholder="dd/mm/year" />
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label asp-for="Degree" class="cols-sm-2 control-label">Dagree</label>
                        <div class="cols-sm-10">
                            <div class="input-group">
                                <span asp-validation-for="Degree" class="input-group-addon"><i class="fas fa-graduation-cap" aria-hidden="true"></i></span>
                                <input asp-for="Degree" type="text" class="form-control" placeholder="Enter Your Degree" />
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label asp-for="Institution" class="cols-sm-2 control-label">Institution</label>
                        <div class="cols-sm-10">
                            <div class="input-group">
                                <span asp-validation-for="Institution" class="input-group-addon"><i class="fas fa-university" aria-hidden="true"></i></span>
                                <input asp-for="Institution" type="text" class="form-control" placeholder="Enter Your Institution" />
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label asp-for="Graduated" class="cols-sm-2 control-label">Graduated</label>
                        <div class="cols-sm-10">
                            <div class="input-group">
                                <span asp-validation-for="Graduated" class="input-group-addon"><i class="fas fa-calendar-alt" aria-hidden="true"></i></span>
                                <input asp-for="Graduated" type="date" class="form-control" />
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label asp-for="About" class="cols-sm-2 control-label">About The Teacher</label>
                        <div class="cols-sm-10">
                            <div class="input-group">
                                <span asp-validation-for="About" class="input-group-addon"><i class="fas fa-info" aria-hidden="true"></i></span>
                                <input asp-for="About" type="text" class="form-control" placeholder="Tell us about your self" />
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label asp-for="LessonPrice" class="cols-sm-2 control-label">Price</label>
                        <div class="cols-sm-10">
                            <div class="input-group">
                                <span asp-validation-for="LessonPrice" class="input-group-addon"><i class="fas fa-dollar-sign" aria-hidden="true"></i></span>
                                <input asp-for="LessonPrice" type="text" class="form-control" placeholder="Lesson Price" />
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label asp-for="ImagePath" class="cols-sm-2 control-label">Image URL</label>
                        <div class="cols-sm-10">
                            <div class="input-group">
                                <span asp-validation-for="ImagePath" class="input-group-addon"><i class="fas fa-image" aria-hidden="true"></i></span>
                                <input asp-for="ImagePath" type="text" class="form-control" placeholder="Share with us your image" />
                            </div>
                        </div>
                    </div>


                    <div class="form-group ">
                        <button asp-controller="AdminPanel" asp-action="Dashboard" input type="submit" value="CreateTeacher" class="btn btn-primary btn-lg btn-block login-button">Register</button>
                    </div>


                    <div class="login-register">
                        <a asp-area="" asp-controller="UserPanel" asp-action="UserLogin"><i class="fas fa-sign-in-alt"></i> Login</a>
                    </div>
                </form>
            </div>
        </div>
    </div>

            <script type="text/javascript" src="assets/js/bootstrap.js"></script>
</body>
</html>

TeacherApp/Views/AdminPanel/Dashboard.cshtml
@model TeacherApp.Models.Person

@{
    ViewData["Title"] = "Dashboard";

}
<br />
<html>
<head>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="~/js/Admin.js"></script>
    <link rel="stylesheet" type="text/css" href="~/css/adminDashboard.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="~/lib/bootstrap/dist/css/bootstrap.css">
    <!-- Website CSS style -->
    <link rel="stylesheet" type="text/css" href="~/css/site.css">
    <!-- Website Font style -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <!-- Google Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>
</head>
<body id="Dashboard">
    <div class="container-fluid main-container">
        <div class="col-md-2 sidebar">
            <div class="row">
                <!-- uncomment code for absolute positioning tweek see top comment in css -->
                <div class="absolute-wrapper"> </div>
                <!-- Menu -->
                <div class="side-menu">
                    <nav class="navbar navbar-default" role="navigation">
                        <!-- Main Menu -->
                        <div class="side-menu-container">
                            <div class="profile-sidebar">
                                <!-- SIDEBAR USERPIC -->
                                <div class="profile-userpic">
                                    <img src="https://brockportchamber.org/wp-content/uploads/2015/11/user.png" class="img-thumbnail" alt="profilepic">
                                </div>
                                <!-- END SIDEBAR USERPIC -->
                                <!-- SIDEBAR USER TITLE -->
                                <div class="profile-usertitle">
                                    <div class="profile-usertitle-name">
                                        <a class="dropdown-toggle" id="dashboredUserName" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <span class="caret"></span></a>
                                    </div>

                                </div>
                                <!-- END SIDEBAR USER TITLE -->

                            </div>
                            <div class="side-menu-container">
                                <ul class="nav navbar-nav">
                                    <li class="active"><a href="#"><span class="glyphicon glyphicon-dashboard"></span> Dashboard</a></li>
                                    <li><a asp-controller="UserPanel" asp-action="PersonIndex"><span class="fas fa-user"></span> Users</a></li>
                                    <li><a asp-controller="Teachers" asp-action="Index"><span class="fas fa-user-graduate"></span> Teachers</a></li>
                                    <li><a asp-controller="Courses" asp-action="Index"><span class="fas fa-book-open"></span> Courses</a></li>
                                </ul>
                            </div><!-- /.navbar-collapse -->
                    </nav>
                </div>
            </div>
        </div>
        <div class="col-md-10 content">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Admin Dashboard
                </div>
                <div class="panel-body">
                    <font color="black"> Hellow Admin check out your toolbar </font>
                </div>
            </div>
        </div>
    </div>
    <script src="~/js/User/User.js"></script>
</body>
</html>