TeacherApp/Controllers/TeachersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TeacherApp.Models;

namespace TeacherApp.Controllers
{
    public class TeachersController : Controller
    {
        private readonly TeacherAppContext _context;

        public TeachersController(TeacherAppContext context)
        {
            _context = context;
        }

        // GET: Teachers
        public async Task<IActionResult> Index(string searchString)
        {

            var teachers = from teacher in _context.Teachers
                            select teacher;

            if (!String.IsNullOrEmpty(searchString))
            {
                teachers = teachers.Where(t => t.FullName().Contains(searchString));
            }

            return View(await teachers.ToListAsync());

        }

        [HttpPost]
        public async Task<IActionResult> AddReview(int teacherID, string text, int rating)
        {
            // test user login
            if (Request.Cookies["userID"] == null)
            {
                Response.StatusCode = (int) HttpStatusCode.BadRequest;
                return Json(new { status = "error", message = "Please sign in to submit a review" });
            }
            int personID;

            // try to get userID from cookie
            try
            {
                personID = Int32.Parse(Request.Cookies["userID"]);
            }
            catch (Exception e)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new { status = "error", message = "Failed to get user details. " + e.Message });
            }

            Teacher teacher = await _context.Teachers
                .SingleAsync(t => t.ID == teacherID);
            _context.Entry(teacher)
                .Collection(t => t.Reviews)
                .Load();
            Person person = await _context.Persons
                .SingleAsync(p => p.ID == personID);

            var previousReview = from r in _context.Reviews
                                 where r.PersonID == person.ID
                                 where r.TeacherID == teacher.ID
                                 select r;
            // a review already exists for this user
            if (previousReview.ToList().Count > 0)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new
                {
                    status = "error",
                    message = "A review for " + teacher.FullName() + " Already exists from user"
                });
            }

            Review review = new Review
            {
                Published = DateTime.Now,
                Teacher = teacher,
                Rating = rating,
                ReviewContent = text,
                Person = person,
            };

            // will also add a new entry to Reviews table
            teacher.Reviews.Add(review);
            person.ReviewsSubmittedByUser.Add(review);
            _context.Reviews.Add(review);
            teacher.UpdateRating();
            _context.SaveChanges();
            Response.StatusCode = (int)HttpStatusCode.OK;
            return Json(new
            {
                status = "success",
                message = "review submited successfuly"
            });
        }

        // GET: Teachers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teachers
                .SingleOrDefaultAsync(m => m.ID == id);

            if (teacher == null)
            {
                return NotFound();
            }

            // load teacher reviews 
            _context.Entry(teacher)
                .Collection(t => t.Reviews)
                .Load();

            // load teacher courses
            _context.Entry(teacher)
                .Collection(t => t.TeachersCourses)
                .Load();

            // load person for all teacher reviews
            var teacherReviews = _context.Reviews.Where(r => r.TeacherID == id);
            foreach (var r in teacherReviews)
            {
                _context.Entry(r).Reference(x => x.Person).Load();
            }
          

            return View(teacher);
        }

        // GET: Teachers/Create
        public IActionResult Create()
        {
            return View();
        }       
        // GET: Teachers/AllTeachers
        public IActionResult AllTeachers()
        {
            return View();
        }

        // POST: Teachers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,FirstName,LastName,Password,Phone,Gender,Email,Address,DateOfBirth,Degree,Institution,ActiveSince,Enrolled,Graduated,Rating,About,LessonPrice,ImagePath")] Teacher teacher)
        {
            if (ModelState.IsValid)
            {
                _context.Add(teacher);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(teacher);
        }

        // GET: Teachers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teachers.SingleOrDefaultAsync(m => m.ID == id);
            if (teacher == null)
            {
                return NotFound();
            }
            return View(teacher);
        }

        // POST: Teachers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,FirstName,LastName,Password,Phone,Gender,Email,Address,DateOfBirth,Degree,Institution,ActiveSince,Enrolled,Graduated,Rating,About,LessonPrice,ImagePath")] Teacher teacher)
        {
            if (id != teacher.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(teacher);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeacherExists(teacher.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(teacher);
        }

        // GET: Teachers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teachers
                .SingleOrDefaultAsync(m => m.ID == id);
            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacher);
        }

        // POST: Teachers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var teacher = await _context.Teachers.SingleOrDefaultAsync(m => m.ID == id);
            _context.Teachers.Remove(teacher);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TeacherExists(int id)
        {
            return _context.Teachers.Any(e => e.ID == id);
        }
    }
}

TeacherApp/Controllers/UserPanelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using TeacherApp.Models;

namespace TeacherApp.Controllers
{
    public class UserPanelController : Controller
    {
        private readonly TeacherAppContext _context;

        public UserPanelController(TeacherAppContext context)
        {
            _context = context;
        }


        public IActionResult Index()
        {
            return View();
        }


        public IActionResult UserLogin()
        {
            return View();
        }



        [HttpPost]
        public int UserLogin(string username, string password)
        {
            Person p = (from Person in _context.Persons
                                   where Person.Email == username && Person.Password == password
                                   select Person).FirstOrDefault();

            if (p != null)
            {
                return p.ID;
            }
            return 0;
        }

        public IActionResult UserSignUp()
        {
            return View();
        }

        public IActionResult SearchBestOffer()
        {
            return View();
        }

        //[HttpPost]
        //public JsonResult SearchBestOffer(string courseName)
        //{
        //    // join query - the join is represented in teacherCourse model defention iteself
        //    var c = from teacherCourse in _context.TeachersCourses
        //            where teacherCourse.Course.CourseName.ToLower() == courseName.ToLower()
        //            orderby teacherCourse.Teacher.LessonPrice ascending
        //            select new
        //            {
        //                teacher = teacherCourse.Teacher.FullName(),
        //                price = teacherCourse.Teacher.LessonPrice,
        //                rating = teacherCourse.Teacher.Rating
        //            };
        //    if (c == null)
        //    {
        //        return null;
        //    }
        //    return Json(c.ToList());
        //}
        [HttpPost]
        public IActionResult SearchBestOffer(string courseName)
        {
            List<Dictionary<string, string>> results = new List<Dictionary<string, string>>();
            ViewData["courseName"] = courseName;
            ViewBag.results = results;
            if (courseName == null) { return View(); }
            // join query - the join is represented in teacherCourse model defention iteself
            var c = from teacherCourse in _context.TeachersCourses
                    where teacherCourse.Course.CourseName.ToLower() == courseName.ToLower()
                    orderby teacherCourse.Teacher.LessonPrice ascending
                    select new
                    {
                        teacher = teacherCourse.Teacher.FullName(),
                        price = teacherCourse.Teacher.LessonPrice,
                        rating = teacherCourse.Teacher.Rating,
                    };
            if (c == null) { return View(); }
            foreach (var result in c)
            {
                results.Add(new Dictionary<string, string>() { { "teacher", result.teacher },{ "price", result.price.ToString() }, { "rating", result.rating.ToString() } });
                //results.Add("teacher", result.teacher);
                //results.Add("price", result.price.ToString());
                //results.Add("rating", result.rating.ToString());
            };
            return View();
        }

        public IActionResult UserDashboard()
        {
                return View();
        }


        // POST: People/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UserSignUp([Bind("ID,FirstName,LastName,Password,Phone,Gender,Email,Address,DateOfBirth,Degree,Institution")] Person person)
        {
            if (ModelState.IsValid)
            {
                _context.Add(person);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(person);
        }


        // GET: Reviews/Create
        public IActionResult CreateReview()
        {
            return View();
        }

        // POST: Reviews/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateReview([Bind("ReviewID,Published,Rating,TeacherID,ReviewContent")] Review review)
        {
            if (ModelState.IsValid)
            {
                _context.Add(review);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(review);
        }


        // GET: People
        public async Task<IActionResult> PersonIndex()
        {
            return View(await _context.Persons.ToListAsync());
        }

        // GET: People/Details/5
        public async Task<IActionResult> PersonDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.Persons
                .SingleOrDefaultAsync(m => m.ID == id);
            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }


        // GET: People/Edit/5
        public async Task<IActionResult> EditPerson(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.Persons.SingleOrDefaultAsync(m => m.ID == id);
            if (person == null)
            {
                return NotFound();
            }
            return View(person);
        }

        // POST: People/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPerson(int id, [Bind("ID,FirstName,LastName,Password,Phone,Gender,Email,Address,DateOfBirth,IsAdmin")] Person person)
        {
            if (id != person.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(person);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonExists(person.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(person);
        }

        // GET: People/Delete/5
        public async Task<IActionResult> DeletePerson(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.Persons
                .SingleOrDefaultAsync(m => m.ID == id);
            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

        // POST: People/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var person = await _context.Persons.SingleOrDefaultAsync(m => m.ID == id);
            _context.Persons.Remove(person);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PersonExists(int id)
        {
            return _context.Persons.Any(e => e.ID == id);
        }

        public async Task<IActionResult> userTeacherIndex(string searchString)
        {

            var teachers = from teacher in _context.Teachers
                           select teacher;

            if (!String.IsNullOrEmpty(searchString))
            {
                teachers = teachers.Where(t => t.FullName().Contains(searchString));
            }

            return View(await teachers.ToListAsync());

        }
    }
}

TeacherApp/Views/UserPanel/DeletePerson.cshtml
@model TeacherApp.Models.Person

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Person</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Degree)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Degree)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Institution)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Institution)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input asp-controller="UserPanel" asp-action="PersonIndex" type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-controller="UserPanel" asp-action="PersonIndex">Back to List</a>
    </form>
</div>

TeacherApp/Views/UserPanel/EditPerson.cshtml
@model TeacherApp.Models.Person

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Person</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label"></label>
                <input asp-for="DateOfBirth" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-check">
                <label asp-for="IsAdmin" class="form-check-label"></label>
                <input asp-for="IsAdmin" class="form-check-input" type="checkbox" />
                <span asp-validation-for="IsAdmin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-controller="UserPanel" asp-action="PersonIndex" type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="PersonIndex">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TeacherApp/Views/UserPanel/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<html lang="en">
<head>
  
    <link rel="stylesheet" type="text/css" href="~/css/UserSignUp.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="assets/css/bootstrap.css">
    <!-- Website CSS style -->
    <link rel="stylesheet" type="text/css" href="assets/css/main.css">
    <!-- Website Font style -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <!-- Google Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>
</head>
<body>

</body>
</html>

TeacherApp/Views/UserPanel/PersonDetails.cshtml
@model TeacherApp.Models.Person

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Person</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Degree)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Degree)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Institution)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Institution)
        </dd>
    </dl>
</div>
<div>
    <a asp-controller="UserPanel" asp-action="EditPerson" asp-route-id="@Model.ID">Edit</a> |
    <a asp-controller="UserPanel" asp-action="PersonIndex">Back to List</a>
</div>

TeacherApp/Views/UserPanel/PersonIndex.cshtml
@model IEnumerable<TeacherApp.Models.Person>
@{
    ViewData["Title"] = "PersonIndex";
}
<h2>Index</h2>

<p>
    <a asp-controller="UserPanel" asp-action="UserSignUp">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfBirth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsAdmin)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Phone)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Gender)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfBirth)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsAdmin)
                </td>
                <td>
                    <a asp-controller="UserPanel" asp-action="EditPerson" asp-route-id="@item.ID">Edit</a> |
                    <a asp-controller="UserPanel" asp-action="PersonDetails" asp-route-id="@item.ID">Details</a> |
                    <a asp-controller="UserPanel" asp-action="DeletePerson" asp-route-id="@item.ID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

TeacherApp/Views/UserPanel/userTeacherIndex.cshtml
@model IEnumerable<TeacherApp.Models.Teacher>

@{
    ViewData["Title"] = "Our Teachers";
    Layout = "~/Views/Shared/AfterLoginLayout.cshtml";
}

<h2>Our Teachers</h2>


<form asp-controller="Teachers" asp-action="Index">
    <p>
        Look for a teacher: <input type="text" name="searchString">
        <input type="submit" value="Search" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfBirth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Degree)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Institution)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Graduated)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rating)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.About)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LessonPrice)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Phone)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Gender)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfBirth)
                </td>
                <td>
                    @Html.DisplayNameFor(model => model.Degree)
                </td>
                <td>
                    @Html.DisplayNameFor(model => model.Institution)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Graduated)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rating)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.About)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LessonPrice)
                </td>
            </tr>
        }
    </tbody>
</table>